name: Cron Scheduler

on:
  schedule:
    - cron: "15 5 * * *" # Avoid 12AM queue
    - cron: "15 8 * * 3" # Promote on Wednesdays
  workflow_dispatch:

jobs:
  trigger-nightly-update:
    if: github.event.schedule == '15 5 * * *' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/update.yml
    with:
      target_branch: "nightly"
    secrets: inherit

  trigger-weekly-promotion:
    if: github.event.schedule == '15 8 * * 3'
    uses: ./.github/workflows/promote.yml
    secrets: inherit
